language: java

dist: trusty
sudo: required

jdk:
        - oraclejdk8

env:
        - SONARHOME=/tmp/sonarqube-6.7.4   SONARAPI=SqApi67
        - SONARHOME=/tmp/sonarqube-7.0     SONARAPI=SqApi67
        - SONARHOME=/tmp/sonarqube-7.1     SONARAPI=SqApi67
        - SONARHOME=/tmp/sonarqube-7.2     SONARAPI=SqApi67

matrix:
    fast_finish: true
#    allow_failures:
#        - env: SONARHOME=/tmp/sonarqube-7.0-RC1 SONARAPI=SqApi67

# shorten the VM hostname with the new workaround
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
addons:
     hosts:
        - myshorthost
     hostname: myshorthost

before_cache:
        # remove all the artifacts that are installed in local repo because of mvn deploy
        - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube-plugins/cxx
        - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
cache:
    directories:
        - '$HOME/.m2/repository'

before_install:
        - cat /etc/hosts # optionally check the content
        # Boost 1.55 is pre-installed on Ubuntu Trusty
        #- travis_retry sudo apt-add-repository -y ppa:boost-latest/ppa
        #- travis_retry sudo apt-get -qq update
        #- travis_retry sudo apt-get -qq install boost1.55
        - travis_retry sudo apt-get -qq install libxml2-utils

install:
        - pushd /tmp
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-6.7.4.zip
        - unzip -qq sonarqube-6.7.4.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-7.0.zip
        - unzip -qq sonarqube-7.0.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-7.1.zip
        - unzip -qq sonarqube-7.1.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-7.2.zip
        - unzip -qq sonarqube-7.2.zip
        - travis_retry wget -q https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.1.0.1141.zip
        - unzip -qq sonar-scanner-cli-3.1.0.1141.zip
        - travis_retry wget -q https://github.com/htacg/tidy-html5/archive/5.6.0.zip --output-document=tidy-html5.zip
        - unzip -qq tidy-html5.zip
        - pushd tidy-html5-5.6.0/build/cmake/
        - cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/tidy-html5-5.6.0 && make && make install && PATH=$PATH:/tmp/tidy-html5-5.6.0/bin
        - popd
        - popd

before_script:
        - travis_retry sudo pip install -q requests
        - travis_retry sudo pip install -q behave
        - travis_retry sudo pip install -q colorama

script:
        - env
        - mvn install -B -e -V -DskipTests=true
        - mvn test -B -e -V
        - bash cxx-sensors/src/tools/check_rules.sh
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-scanner-3.1.0.1141/bin TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata behave --no-capture --tags=$SONARAPI

after_failure:
        - cat $SONARHOME/logs/sonar.log
        - find . -name "*.log" | xargs cat
